version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  lint:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/matterpoll/matterpoll
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make check-style

  test:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/matterpoll/matterpoll
    steps:
      - codecov/upload:
        file: {{ coverage_report_filepath }}
      #- checkout
      #- run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      #- run: make test

workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test
